artifacts: /home/stef/hiec/artifacts
results: /home/stef/quest_data/hiec/results
data: /home/stef/quest_data/hiec/data
scratch: /home/stef/quest_data/hiec/scratch
configs: /home/stef/hiec/configs
cv: ${.results}/cv