defaults:
  - filepaths: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - override hydra/launcher: quest_cpu
  - _self_

similarity_score: blosum
dataset: sprhea
toc: v3_folded_pt_ns
cutoffs: [90, 80, 70, 60, 50, 40, 30]
blosum_ub: 5e2
blosum_lb: -2e3

hydra:
  run:
    dir: ${filepaths.clustering}