defaults:
  - filepaths: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - override hydra/launcher: quest_cpu
  - _self_

similarity_score: gsi
dataset: sprhea
toc: v3_folded_pt_ns
cutoffs: [69.141, 22.216, 12.195, 9.155, 8.38, 7.123]

hydra:
  run:
    dir: ${filepaths.clustering}