defaults:
  - filepaths: base
  - override hydra/launcher: quest_cpu
  - _self_

tracking_uri: file:///projects/p30041/spn1560/hiec/results/runs
run_id: ???
radial_mask: False
r_hop: 1

hydra:
  sweeper:
    params:
      run_id: 84dea227b45b46fb80a5d5559798ff64,4766fb380a3e4cd0b2735be4f1d5ee15
  sweep:
    dir: ${filepaths.results}/embeddings
    subdir: ${...run_id}/radial_mask_${...radial_mask}/r_hop_${...r_hop}
  run:
    dir: ${filepaths.results}/embeddings/${...run_id}/radial_mask_${...radial_mask}/r_hop_${...r_hop}
  job:
    chdir: True