dirs:
  artifacts: /home/stef/hiec/artifacts
  results: /home/stef/quest_data/hiec/results
  data: /home/stef/quest_data/hiec/data
  scratch: /home/stef/quest_data/hiec/scratch
  configs: /home/stef/hiec/configs

subdirs:
  artifacts:
    - clustering
    - named_model_hps
  results:
    - embeddings
    - model_evals
    - sim_mats
    - trained_models
  data:
    - erxprot
    - halogenase
    - new
    - price
    - sprhea