defaults:
  - filepaths: base
  - override hydra/launcher: quest_gpu
  - _self_

tracking_uri: file:///projects/p30041/spn1560/hiec/results/runs

hydra:
  sweeper:
    params:
      run_id: 
  run:
    dir: ${filepaths.results}/predictions/${...run_id}
  job:
    chdir: True