defaults:
  - data: sprhea_random
  - filepaths: base
  - _self_

hydra:
  sweep:
    dir: ${filepaths.split_guides}
    subdir: ${data.subdir_patt}
  run:
    dir: ${filepaths.split_guides}/${data.subdir_patt}
  job:
    chdir: True