defaults:
  - data: ???
  - filepaths: base
  - override hydra/launcher: quest_cpu
  - _self_

hydra:
  sweep:
    dir: ${filepaths.scratch}
    subdir: ${data.subdir_patt}
  run:
    dir: ${filepaths.scratch}/${data.subdir_patt}
  job:
    chdir: True