defaults:
  - filepaths: base
  - training: base
  - data: ???
  - model: ???
  - override hydra/hydra_logging: disabled # Redundant w/ mlflow
  - override hydra/job_logging: disabled # Redundant w/ mlflow
  - override hydra/launcher: quest_gpu
  - _self_

exp: null

hydra:
  output_subdir: null # Redundant w/ mlflow
  run:
    dir: ${filepaths.scratch} # Redundant w/ mlflow
  sweep:
    dir: ${filepaths.scratch} # Redundant w/ mlflow